name: Check build

on:
  [pull_request, push]

jobs:
  check_build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0
          - 4.11.0
          - 4.10.1
          - 4.09.1
          - 4.08.1
          - 4.07.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Build
        run: |
          set -x
          ./scripts/depends.sh
          eval $(opam env)

          opam pin add . -y
